server:
  port: 8089
  ssl:
    key-store: classpath:www.yisabang.com.jks
    key-password: 4uu0r3ip5k70
    key-store-type: JKS
spring:
  profiles: prod
  datasource:
    # 如果存在多个数据源，监控的时候可以通过名字来区分开来
    name: mysql
    # 连接数据库的url
    url: jdbc:mysql://132.232.42.204:3306/yi_san_bang?characterEncoding=utf-8&serverTimezone=GMT%2B8
    # 连接数据库的账号
    username: root
    # 连接数据库的密码
    password: Yisabang123.
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 132.232.42.204
    port: 6379
    # redis密码，默认为空
    password: Yisabang123.Redis

swagger:
  host: 132.232.42.204:8089
  show: true

logging:
  level:
    ROOT: info
    com.example: trace

