server:
  port: 8088
spring:
  profiles: dev
  datasource:
    # 如果存在多个数据源，监控的时候可以通过名字来区分开来
    name: mysql
    # 连接数据库的url
    url: jdbc:mysql://192.168.0.128:3307/yi_san_bang?characterEncoding=utf-8&serverTimezone=GMT%2B8
    # 连接数据库的账号
    username: root
    # 连接数据库的密码
    password: Wlt123++
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 119.3.254.171
    port: 6379
    # redis密码，默认为空
    password: wlt123..

swagger:
  host: 119.3.254.171:8088
  show: true

logging:
  level:
    ROOT: info
    com.example: trace