spring:
  profiles:
    active: test
  jackson:
    time-zone: GMT+8

  devtools:
    restart:
      enabled: true  #设置开启热部署
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            #默认或是自己改名字都行
            instanceName: DefaultQuartzScheduler
            #如果使用集群，instanceId必须唯一，设置成AUTO
            instanceId: AUTO
          jobStore:
            #存储方式使用RAMJobStore,也就是缓存
            class: org.quartz.simpl.RAMJobStore
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    ROOT: info
    com.example: trace
  file:
    name: target/yourlog.log

wx:
  pay:
    appId: wx447bdd8f7d850c06
    mchId: #微信支付商户号
    mchKey: #微信支付商户密钥
    payNotifyURL: #微信支付成功后的回调接口 /order/wxNotify
    refundNotifyURL: #微信退款成功后的回调接口 /refund/wxNotify
    tradeType: JSAPI
    keyPath: # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
    spbillCreateIp: #服务器IP地址
  applet:
    appid: wx447bdd8f7d850c06
    appsecret: 1f8dc966cc30761d60394178a5d58301

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  servlet:
    context-path: /
  max-http-header-size: 81920 # 修改请求头允许的最大值

swagger:
  host: 119.3.254.171:8088
  show: true




